<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>StardropiumChinese</AssemblyName>
    <RootNamespace>StardropiumChinese</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="StardewModdingAPI">
      <HintPath>StardewModdingAPI.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>0Harmony.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
