name: Build Mod

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: StardropiumChinese
        path: bin/Release/net6.0/StardropiumChinese.dll
